### ISSUE TITLE
[Feature suggestion] Automatically scroll to first error after failed build

### ISSUE THREAD

**Issue by trashner** [albertosantini/sublimetext-buildnext#11]
For your consideration.

**Comment by albertosantini** [comment]
Thanks for the feedback.

I think there are two use cases.

- A classical build, for instance a Makefile, where it makes sense to go to the first error.
- Then there is the use case using a linter, maybe executed when you save the file; in this case it would not make sense to scroll to the first error, the cursor should remain where the programmer is editing.

We can resolve it with a preference, like `ST_BUILD_SCROLL_FIRST_ERROR` with default `false`.

If you contribute it, I would glad to merge it, otherwise it is a `won't fix'.
